# Generated by Django 5.0.7 on 2025-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_blog_id_alter_blog_section_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('Recent', 'Recent')], max_length=100),
        ),
    ]
